baseURL = "https://coffeeandcowork.org/"
languageCode = "en-us"
title = "Coffee and Cowork"
timeZone = "America/Detroit"

[params]
  # tagline = "Coffee, once a week, with other people."
  tagline = "One coffee shop. No RSVP. No LinkedIn post about it afterward."
  bluesky = "https://bsky.app/profile/coffeeandcowork.bsky.social"
